name: Release
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@bx-looop'
         
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-npm-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install root dependencies
        run: npm ci

      - name: Install src dependencies
        run: npm ci
        working-directory: ./src
      
      - name: Build src
        run: npm run build
        working-directory: ./src

      - name: Install deploy dependencies
        run: npm ci
        working-directory: ./deploy

      - name: Lint code
        run: npm run lint

      - name: Run Tests
        run: npm run test
        working-directory: ./src
      
      - name: Build deploy
        run: npm run build
        working-directory: ./deploy

      - name: Release
        if: ${{ github.event_name == 'push' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
