name: Publish

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup Node to be used in later actions
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Run npm ci
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Add commit SHA
        run: echo ${GITHUB_SHA} > ./build/git.ver

      - name: Zip build folder
        run: zip -qq -r -j ./bundle.zip ./build/*

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ARTIFACTS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ARTIFACTS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Copy Zip File to looop-artefacts
        run: aws s3 cp bundle.zip s3://looop-artefacts/soil-domain-service/soil-domain-service-0.1.0+${GITHUB_RUN_NUMBER}.zip
